# Separate migration service for production best practices
version: '3.8'

services:
  # Migration service - run once to initialize/migrate database
  handyshop-migrate:
    build:
      context: .
      target: migrator
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - FORCE_SECURE_COOKIES=true
      - HTTPS_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "run", "db:push"]
    restart: "no"  # Run once only

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-handyshop}
      - POSTGRES_USER=${POSTGRES_USER:-handyshop}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-handyshop}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: handyshop-network