name: Build Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger available

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Frontend
      run: npm run build
    
    - name: Build Desktop App for macOS
      run: npx electron-builder --mac --publish=never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: handyshop-macos-dmg
        path: dist-electron/*.dmg
        retention-days: 30
    
    - name: Upload App Directory
      uses: actions/upload-artifact@v4
      with:
        name: handyshop-macos-app
        path: dist-electron/mac/
        retention-days: 30

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Frontend
      run: npm run build
    
    - name: Build Desktop App for Windows
      run: npx electron-builder --win --publish=never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: handyshop-windows-installer
        path: dist-electron/*.exe
        retention-days: 30